apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foorestores.foo.my.domain.com
spec:
  group: foo.my.domain.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: foorestores
    singular: foorestore
    kind: FooRestore
