{{- if not .Values.fail }}
apiVersion: foo.my.domain.com/v1alpha1
kind: FooRestore
metadata:
  labels:
    app: {{ template "test-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "test-chart.fullname" . }}-restore-success
{{- end }}
